import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/toaster";
import { getServerAuthSession } from "@/server/auth";
import { AuthProvider } from "@/lib/AuthProvider";
import { EdgeStoreProvider } from "@/lib/EdgestoreProvider";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
})

export const metadata = {
  title: "BuzzHive",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AuthProvider session={session}>
          <TRPCReactProvider>
            <EdgeStoreProvider>
              {children}
            </EdgeStoreProvider>
            <Toaster />
          </TRPCReactProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
