import "@/styles/globals.css";

import { Roboto_Mono } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto_mono'
})

export const metadata = {
  title: "BuzzHive",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-[#030712] ${roboto_mono.variable}`}>
        <TRPCReactProvider>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
